app:
  name: 'blog-serve'
  version: '1.0.0'
  api:
    prefix: '/api'
    version: 'v1'
  http:
    host: 'localhost'
    port: 3090
    timeout: 5000
  

db:
  postgres:
    host: 'localhost'
    url: 'localhost'
    port: 5432
    database: 'yaml-db'
    username: 'root'
    password: '375999**@Li'
    synchronize: true
  mysql:
    host: 'localhost'
    url: 'localhost'
    port: 3306
    database: 'liks_blog'
    username: 'root'
    password: '375999**@Li'
    synchronize: true